"""updated users model

Revision ID: 25cf77013934
Revises: 6b17596e4c9b
Create Date: 2022-05-20 14:31:32.087940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cf77013934'
down_revision = '6b17596e4c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_details', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_details', 'password_hash')
    # ### end Alembic commands ###
