"""altered users db, removed redunted col

Revision ID: 3b2038a2f169
Revises: 477e78e0e2cb
Create Date: 2022-07-29 22:14:08.755082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2038a2f169'
down_revision = '477e78e0e2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
