"""user profile picture col added

Revision ID: 477e78e0e2cb
Revises: 8005e57ee806
Create Date: 2022-07-28 15:52:08.439514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477e78e0e2cb'
down_revision = '8005e57ee806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
