"""removed unneeded columns

Revision ID: 5ea21b72ffbf
Revises: c109257d4c07
Create Date: 2022-07-25 14:58:29.511135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea21b72ffbf'
down_revision = 'c109257d4c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_details', 'first_name')
    op.drop_column('users_details', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_details', sa.Column('last_name', sa.VARCHAR(length=374), autoincrement=False, nullable=False))
    op.add_column('users_details', sa.Column('first_name', sa.VARCHAR(length=373), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
