"""create users model

Revision ID: 6b17596e4c9b
Revises: 
Create Date: 2022-05-20 14:19:08.809230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b17596e4c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=373), nullable=False),
    sa.Column('last_name', sa.String(length=374), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_details')
    # ### end Alembic commands ###
