"""foreignkey, one-to-many relationship: Users linked to Posts

Revision ID: 7cec4b1529ea
Revises: 5ea21b72ffbf
Create Date: 2022-07-26 11:27:20.525242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cec4b1529ea'
down_revision = '5ea21b72ffbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('user_name', sa.String(length=144), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('users_details')
    op.add_column('blog_posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'author_id')
    op.create_table('users_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_details_pkey'),
    sa.UniqueConstraint('slug', name='users_details_slug_key'),
    sa.UniqueConstraint('user_name', name='users_details_user_name_key')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
