"""user table issue: attempt to fix 1

Revision ID: 92082d400344
Revises: 7cec4b1529ea
Create Date: 2022-07-26 11:35:43.475518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92082d400344'
down_revision = '7cec4b1529ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('user_name', sa.String(length=144), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('users')
    op.drop_constraint('blog_posts_author_id_fkey', 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'users_details', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key('blog_posts_author_id_fkey', 'blog_posts', 'users', ['author_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=144), autoincrement=False, nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('slug', name='users_slug_key'),
    sa.UniqueConstraint('user_name', name='users_user_name_key')
    )
    op.drop_table('users_details')
    # ### end Alembic commands ###
