"""changed table name

Revision ID: ae2032f26613
Revises: 980ad0bc5e76
Create Date: 2022-05-01 12:27:24.487761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae2032f26613'
down_revision = '980ad0bc5e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=373), nullable=False),
    sa.Column('last_name', sa.String(length=374), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=373), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=374), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('slug', name='users_slug_key')
    )
    op.drop_table('signup users')
    # ### end Alembic commands ###
