"""removed email as username will be used instead

Revision ID: c109257d4c07
Revises: 1cec24edc014
Create Date: 2022-07-25 13:55:01.366378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c109257d4c07'
down_revision = '1cec24edc014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_details_email_key', 'users_details', type_='unique')
    op.drop_column('users_details', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_details', sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_details_email_key', 'users_details', ['email'])
    # ### end Alembic commands ###
