"""user_name correction

Revision ID: da0eb276815b
Revises: 25cf77013934
Create Date: 2022-07-05 13:54:54.960714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0eb276815b'
down_revision = '25cf77013934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_details', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_details', type_='unique')
    # ### end Alembic commands ###
